name: Fallback Workflow

on:
  schedule:
    - cron: "45 7 * * 6" # Runs every Sunday at 7:45 AM (15 minutes after the main workflow)
  workflow_dispatch: # Allows manual trigger

jobs:
  fallback-job:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set the GH_TOKEN environment variable

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y  # Ensure GitHub CLI is installed

      - name: Check if Main Workflow has been triggered
        id: check_main_workflow
        run: |
          # GitHub API request to check the status of the last run of the main workflow
          last_run=$(gh api repos/${{ github.repository }}/actions/workflows/nodejs.yml/runs \
            --jq '.workflow_runs[0].status')

          echo "Last run status: $last_run"

          if [[ "$last_run" == "completed" || "$last_run" == "in_progress" ]]; then
            echo "last_run=completed_or_in_progress" >> $GITHUB_ENV
            exit 0
          else
            echo "last_run=not_started" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        if: ${{ env.last_run == 'not_started' }}
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: ${{ env.last_run == 'not_started' }}
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        if: ${{ env.last_run == 'not_started' }}
        run: npm install

      - name: Run Puppeteer script
        if: ${{ env.last_run == 'not_started' }}
        env:
          DNI: ${{ secrets.DNI }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node register.js
